// Handleliste produktdatabase
// 500+ norske dagligvarer med kategorier, ikoner og kvitteringsalias

export const PRODUCTS = [

  // ─── MEIERI ───────────────────────────────────────────────────────────────
  { navn: "Lettmelk", ikon: "🥛", kat: "meieri", alias: ["lettmelk","tine lettmelk","q lettmelk","prior lettmelk","lett melk","1,2% melk","laktosefri lettmelk"] },
  { navn: "Helmelk", ikon: "🥛", kat: "meieri", alias: ["helmelk","tine helmelk","q helmelk","hel melk","3,5% melk","seterrømme melk"] },
  { navn: "Skummetmelk", ikon: "🥛", kat: "meieri", alias: ["skummetmelk","tine skummetmelk","0,5% melk","skummet melk"] },
  { navn: "Melk", ikon: "🥛", kat: "meieri", alias: ["melk","ekologisk melk","økologisk melk","oatly","havremelk","mandelmelk","soyamelk","rispmelk","plantemelk"] },
  { navn: "Smør", ikon: "🧈", kat: "meieri", alias: ["smør","tine smør","meierismør","normanna smør","lurpak","laktosefritt smør"] },
  { navn: "Margarin", ikon: "🧈", kat: "meieri", alias: ["margarin","soft flora","flora","vita hjertego","myk margarin"] },
  { navn: "Egg", ikon: "🥚", kat: "meieri", alias: ["egg","egg 6pk","egg 10pk","egg 12pk","prior egg","norgården egg","frittgående egg","økologiske egg","store egg","medium egg"] },
  { navn: "Norvegia", ikon: "🧀", kat: "meieri", alias: ["norvegia","norvegia 500g","norvegia 1kg","norvegia skivet","norvegia revet"] },
  { navn: "Jarlsberg", ikon: "🧀", kat: "meieri", alias: ["jarlsberg","jarlsberg 500g","jarlsberg skivet"] },
  { navn: "Brunost", ikon: "🧀", kat: "meieri", alias: ["brunost","gudbrandsdalsost","ekte geitost","fløtemysost","tine brunost","ski queen"] },
  { navn: "Cottage cheese", ikon: "🧀", kat: "meieri", alias: ["cottage cheese","tine cottage","q cottage","milram cottage"] },
  { navn: "Kremost", ikon: "🧀", kat: "meieri", alias: ["kremost","philadelphia","buko","castello kremost","naturell kremost"] },
  { navn: "Mozzarella", ikon: "🧀", kat: "meieri", alias: ["mozzarella","galbani mozzarella","president mozzarella","mozzarella light"] },
  { navn: "Parmesan", ikon: "🧀", kat: "meieri", alias: ["parmesan","parmigiano","grana padano","parmesan revet"] },
  { navn: "Fetaost", ikon: "🧀", kat: "meieri", alias: ["fetaost","feta","apetina","arla feta","fetaost i lake"] },
  { navn: "Rømme", ikon: "🫙", kat: "meieri", alias: ["rømme","tine rømme","q rømme","lettrømme","seterrømme","crème fraîche","creme fraiche"] },
  { navn: "Fløte", ikon: "🫙", kat: "meieri", alias: ["fløte","matfløte","tine fløte","q fløte","uht fløte"] },
  { navn: "Kremfløte", ikon: "🫙", kat: "meieri", alias: ["kremfløte","krem","piskefløte","tine kremfløte","q kremfløte","happy whip"] },
  { navn: "Yoghurt naturell", ikon: "🍶", kat: "meieri", alias: ["yoghurt naturell","yoplait naturell","tine yoghurt","q yoghurt naturell","biola","skyr naturell"] },
  { navn: "Yoghurt jordbær", ikon: "🍶", kat: "meieri", alias: ["yoghurt jordbær","strawberry yoghurt","go'morgen jordbær"] },
  { navn: "Skyr", ikon: "🍶", kat: "meieri", alias: ["skyr","arla skyr","icelandic provisions","skyr vanilje","skyr jordbær","skyr bringebær"] },
  { navn: "Kesam", ikon: "🫙", kat: "meieri", alias: ["kesam","tine kesam","q kesam","kvark"] },
  { navn: "Seterrømme", ikon: "🫙", kat: "meieri", alias: ["seterrømme","seter rømme","tine seterrømme"] },
  { navn: "Crème fraîche", ikon: "🫙", kat: "meieri", alias: ["creme fraiche","crème fraîche","lett creme fraiche"] },
  { navn: "Smøreost", ikon: "🧀", kat: "meieri", alias: ["smøreost","kavli smøreost","tine smøreost","ekte smøreost"] },
  { navn: "Pultost", ikon: "🧀", kat: "meieri", alias: ["pultost","snøfrisk","geiteost","chèvre"] },
  { navn: "Laktosefri melk", ikon: "🥛", kat: "meieri", alias: ["laktosefri melk","laktosfri","laktosefri lettmelk","laktosefri helmelk"] },
  { navn: "Plantebasert yoghurt", ikon: "🍶", kat: "meieri", alias: ["soya yoghurt","havre yoghurt","kokos yoghurt","alpro yoghurt"] },

  // ─── BRØD & BAKERI ────────────────────────────────────────────────────────
  { navn: "Grovbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["grovbrød","grov sandwich","hatting grov","åpent bakeri grov","mesterbakeren grov","frøbrød"] },
  { navn: "Loff", ikon: "🍞", kat: "brod-bakeri", alias: ["loff","toastbrød","hvit sandwich","baguette loff","loffskiver"] },
  { navn: "Rundstykker", ikon: "🥖", kat: "brod-bakeri", alias: ["rundstykker","horn","hamburgerbrød","pølsebrød","brioche"] },
  { navn: "Knekkebrød", ikon: "🫓", kat: "brod-bakeri", alias: ["knekkebrød","wasa","ryvita","finn crisp","solgud","mester crispbread"] },
  { navn: "Pitabrød", ikon: "🫓", kat: "brod-bakeri", alias: ["pita","pitabrød","pita lompe","libanesisk brød","flatbrød"] },
  { navn: "Wraps", ikon: "🫓", kat: "brod-bakeri", alias: ["wraps","tortilla","lefse","hvete tortilla","maistortilla","old el paso tortilla"] },
  { navn: "Bagel", ikon: "🥯", kat: "brod-bakeri", alias: ["bagel","bagels","new york bagel"] },
  { navn: "Croissant", ikon: "🥐", kat: "brod-bakeri", alias: ["croissant","butter croissant","smørcroissant"] },
  { navn: "Brioche", ikon: "🍞", kat: "brod-bakeri", alias: ["brioche","briochebrød","franske boller"] },
  { navn: "Surdeig", ikon: "🍞", kat: "brod-bakeri", alias: ["surdeig","surdeigsbrød","surdeig landbrød","åpent bakeri surdeig"] },
  { navn: "Baguette", ikon: "🥖", kat: "brod-bakeri", alias: ["baguette","fransk baguette","bake off baguette","steinovnsbaguette"] },
  { navn: "Ciabatta", ikon: "🥖", kat: "brod-bakeri", alias: ["ciabatta","ciabattabrød","italiensk brød"] },
  { navn: "Boller", ikon: "🥐", kat: "brod-bakeri", alias: ["boller","hveteboller","skoleboller","kanelboller","kardemommeboller","sukkerboller"] },
  { navn: "Kneippbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["kneipp","kneippbrød","grovkneipp"] },
  { navn: "Frokostbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["frokostbrød","7-korn","frøbrød","solsikkebrød"] },
  { navn: "Lefse", ikon: "🫓", kat: "brod-bakeri", alias: ["lefse","potetlefse","tjukklefse","lompe"] },
  { navn: "Polarbrød", ikon: "🫓", kat: "brod-bakeri", alias: ["polarbrød","polar","polarbröd"] },

  // ─── FRUKT & GRØNT ────────────────────────────────────────────────────────
  { navn: "Bananer", ikon: "🍌", kat: "frukt-gront", alias: ["banan","bananer","fairtrade banan","øko banan"] },
  { navn: "Epler", ikon: "🍎", kat: "frukt-gront", alias: ["epler","eple","gala","granny smith","fuji","royal gala","elstar","pink lady"] },
  { navn: "Appelsiner", ikon: "🍊", kat: "frukt-gront", alias: ["appelsin","appelsiner","navel","clementiner","satsumas","mandariner"] },
  { navn: "Sitroner", ikon: "🍋", kat: "frukt-gront", alias: ["sitron","sitroner","lemon"] },
  { navn: "Lime", ikon: "🍋", kat: "frukt-gront", alias: ["lime","limefrukter"] },
  { navn: "Kiwi", ikon: "🥝", kat: "frukt-gront", alias: ["kiwi","kiwifrukt","zespri"] },
  { navn: "Mango", ikon: "🥭", kat: "frukt-gront", alias: ["mango","mangofrukt","alphonso mango"] },
  { navn: "Jordbær", ikon: "🍓", kat: "frukt-gront", alias: ["jordbær","strawberry","jordbær 500g","norske jordbær"] },
  { navn: "Blåbær", ikon: "🫐", kat: "frukt-gront", alias: ["blåbær","blueberry","blåbær 125g"] },
  { navn: "Bringebær", ikon: "🍓", kat: "frukt-gront", alias: ["bringebær","raspberry","bringebær 125g"] },
  { navn: "Druer", ikon: "🍇", kat: "frukt-gront", alias: ["druer","grønne druer","røde druer","seedless grapes","thompson druer"] },
  { navn: "Pære", ikon: "🍐", kat: "frukt-gront", alias: ["pære","pærer","conference","williams pære"] },
  { navn: "Fersken", ikon: "🍑", kat: "frukt-gront", alias: ["fersken","nektarin","plommer"] },
  { navn: "Vannmelon", ikon: "🍉", kat: "frukt-gront", alias: ["vannmelon","melon","honningsmelon","cantaloupe"] },
  { navn: "Ananas", ikon: "🍍", kat: "frukt-gront", alias: ["ananas","fersk ananas","del monte ananas"] },
  { navn: "Avokado", ikon: "🥑", kat: "frukt-gront", alias: ["avokado","avocado","hass avokado"] },
  { navn: "Tomater", ikon: "🍅", kat: "frukt-gront", alias: ["tomater","tomat","cherrytomater","beef tomat","romatomater","soltørkede tomater"] },
  { navn: "Agurk", ikon: "🥒", kat: "frukt-gront", alias: ["agurk","slangeagurk","mini agurk","norsk agurk"] },
  { navn: "Salat", ikon: "🥬", kat: "frukt-gront", alias: ["salat","isbergsalat","rucola","romaine","mixed salat","babysalat","hodesalat","salat mix"] },
  { navn: "Spinat", ikon: "🥬", kat: "frukt-gront", alias: ["spinat","babyspinat","fersk spinat"] },
  { navn: "Brokkoli", ikon: "🥦", kat: "frukt-gront", alias: ["brokkoli","broccoli","broccolini"] },
  { navn: "Blomkål", ikon: "🫛", kat: "frukt-gront", alias: ["blomkål","hvit blomkål","romanesco"] },
  { navn: "Gulrøtter", ikon: "🥕", kat: "frukt-gront", alias: ["gulrot","gulrøtter","mini gulrot","babygulerøtter","råkost gulrot"] },
  { navn: "Løk", ikon: "🧅", kat: "frukt-gront", alias: ["løk","gul løk","kepaløk","rødløk","vårløk","sjalottløk","purreløk"] },
  { navn: "Hvitløk", ikon: "🧄", kat: "frukt-gront", alias: ["hvitløk","hvitløkfedd","hvitløk hode"] },
  { navn: "Paprika", ikon: "🫑", kat: "frukt-gront", alias: ["paprika","rød paprika","gul paprika","grønn paprika","oransje paprika","mini paprika"] },
  { navn: "Poteter", ikon: "🥔", kat: "frukt-gront", alias: ["poteter","potet","mandelpoteter","nypoteter","søtpotet","amadine","asterix","beate"] },
  { navn: "Søtpotet", ikon: "🍠", kat: "frukt-gront", alias: ["søtpotet","sweet potato","boniato"] },
  { navn: "Sopp", ikon: "🍄", kat: "frukt-gront", alias: ["sopp","sjampinjong","champignon","shiitake","portobello","agaricus"] },
  { navn: "Squash", ikon: "🥒", kat: "frukt-gront", alias: ["squash","zucchini","courgette"] },
  { navn: "Aubergine", ikon: "🍆", kat: "frukt-gront", alias: ["aubergine","eggplant"] },
  { navn: "Mais", ikon: "🌽", kat: "frukt-gront", alias: ["mais","frisk mais","maiskolbe","baby corn"] },
  { navn: "Erter", ikon: "🫛", kat: "frukt-gront", alias: ["erter","sukkererter","dampede erter"] },
  { navn: "Ingefær", ikon: "🫚", kat: "frukt-gront", alias: ["ingefær","frisk ingefær","ingefær rot"] },
  { navn: "Selleri", ikon: "🥬", kat: "frukt-gront", alias: ["selleri","stangselleri","knollselleri"] },
  { navn: "Kål", ikon: "🥬", kat: "frukt-gront", alias: ["kål","hodekål","rødkål","kinakål","grønnkål","spissen kål","savoykål"] },
  { navn: "Asparges", ikon: "🌿", kat: "frukt-gront", alias: ["asparges","grønn asparges","hvit asparges"] },
  { navn: "Fennikel", ikon: "🌿", kat: "frukt-gront", alias: ["fennikel","fennikkel"] },
  { navn: "Purre", ikon: "🥬", kat: "frukt-gront", alias: ["purre","purreløk","leek"] },
  { navn: "Reddik", ikon: "🌿", kat: "frukt-gront", alias: ["reddik","radise","daikon"] },
  { navn: "Mais på boks", ikon: "🌽", kat: "frukt-gront", alias: ["mais boks","hermetisk mais","green giant mais"] },

  // ─── KJØTT & FISK ─────────────────────────────────────────────────────────
  { navn: "Kyllingfilet", ikon: "🍗", kat: "kjott-fisk", alias: ["kyllingfilet","kylling filet","norsk kylling","prior kylling filet","strimlet kylling"] },
  { navn: "Kyllinglår", ikon: "🍗", kat: "kjott-fisk", alias: ["kyllinglår","kylling lår","kyllingklubb","kylling ovnstekt"] },
  { navn: "Hel kylling", ikon: "🍗", kat: "kjott-fisk", alias: ["hel kylling","grillkylling","stekekylling","prior hel kylling"] },
  { navn: "Kjøttdeig", ikon: "🥩", kat: "kjott-fisk", alias: ["kjøttdeig","storfe kjøttdeig","svin kjøttdeig","bland kjøttdeig","karbonadedeig","karbonade"] },
  { navn: "Svinekoteletter", ikon: "🥩", kat: "kjott-fisk", alias: ["svinekotlett","svinekoteletter","nakkekoteletter","ribbekoteletter"] },
  { navn: "Svinekjøtt", ikon: "🥩", kat: "kjott-fisk", alias: ["svinekjøtt","svinefilet","svinekarrè","ribbe","svinestek","svinestriper"] },
  { navn: "Biff", ikon: "🥩", kat: "kjott-fisk", alias: ["biff","entrecote","indrefilet","ytrefilet","oksebiff","hamburger","steakbiff"] },
  { navn: "Oksekjøtt", ikon: "🥩", kat: "kjott-fisk", alias: ["oksekjøtt","oksestek","oksegryte","oksehalesuppe","lapskaus kjøtt"] },
  { navn: "Lam", ikon: "🥩", kat: "kjott-fisk", alias: ["lammekjøtt","lammelår","lammekotelett","lammebog","fårikålkjøtt"] },
  { navn: "Bacon", ikon: "🥓", kat: "kjott-fisk", alias: ["bacon","strimlet bacon","frukostbacon","røkt bacon","flat bacon","prior bacon"] },
  { navn: "Pølser", ikon: "🌭", kat: "kjott-fisk", alias: ["pølser","grillpølse","kjøttpølse","wienerpølse","bratwurst","chorizo","pepperoni"] },
  { navn: "Kjøttkaker", ikon: "🍖", kat: "kjott-fisk", alias: ["kjøttkaker","medisterkaker","farsbrød","kjøttpudding"] },
  { navn: "Skinke", ikon: "🍖", kat: "kjott-fisk", alias: ["skinke","kokt skinke","røkt skinke","serranoskinke","prosciutto","bayonneskinke","spekeskinke"] },
  { navn: "Salami", ikon: "🍖", kat: "kjott-fisk", alias: ["salami","italiensk salami","ungarsk salami","pepperoni","fuet"] },
  { navn: "Laks", ikon: "🐟", kat: "kjott-fisk", alias: ["laks","laksefilet","laksesteak","røkt laks","gravlaks","mowi laks"] },
  { navn: "Ørret", ikon: "🐟", kat: "kjott-fisk", alias: ["ørret","fjordørret","regnbueørret","røkt ørret"] },
  { navn: "Torsk", ikon: "🐟", kat: "kjott-fisk", alias: ["torsk","torskefilet","skrei","klippfisk","bacalao","tørrfisk"] },
  { navn: "Sei", ikon: "🐟", kat: "kjott-fisk", alias: ["sei","seifile","seibiff"] },
  { navn: "Makrell", ikon: "🐟", kat: "kjott-fisk", alias: ["makrell","fersk makrell","røkt makrell","makrell i tomat"] },
  { navn: "Reker", ikon: "🦐", kat: "kjott-fisk", alias: ["reker","ferske reker","kokte reker","frosne reker","scampi"] },
  { navn: "Krabbe", ikon: "🦀", kat: "kjott-fisk", alias: ["krabbe","kongekrabbe","taskekrabbe","krabbemat"] },
  { navn: "Fiskebolter", ikon: "🐟", kat: "kjott-fisk", alias: ["fiskeboller","fiskebolle","freia fiskeboller","findus fiskeboller"] },
  { navn: "Fiskepinner", ikon: "🐟", kat: "kjott-fisk", alias: ["fiskepinner","findus fiskepinner","gortons"] },
  { navn: "Fiskekaker", ikon: "🐟", kat: "kjott-fisk", alias: ["fiskekaker","fiskekake","lofoten fiskekaker"] },
  { navn: "Tuna", ikon: "🐟", kat: "kjott-fisk", alias: ["tunfisk","tuna","tuna i vann","tuna i olje","king oscar","calvo"] },
  { navn: "Sardiner", ikon: "🐟", kat: "kjott-fisk", alias: ["sardiner","brisling","king oscar sardiner"] },
  { navn: "Spekepølse", ikon: "🍖", kat: "kjott-fisk", alias: ["spekepølse","fenalår","spekemat","morr"] },

  // ─── TØRRVARER ────────────────────────────────────────────────────────────
  { navn: "Hvetemel", ikon: "🌾", kat: "tørrvarer", alias: ["hvetemel","mel","tipo 00","freia hvetemel","nora hvetemel"] },
  { navn: "Sukker", ikon: "🍬", kat: "tørrvarer", alias: ["sukker","hvitt sukker","strøsukker","melis","brunt sukker","muscovado","kokossukker"] },
  { navn: "Salt", ikon: "🧂", kat: "tørrvarer", alias: ["salt","havsalt","himalayasalt","bordsalt","grovt salt","jodisert salt"] },
  { navn: "Pepper", ikon: "🌶️", kat: "tørrvarer", alias: ["pepper","sort pepper","hvit pepper","pepperkvern","hel pepper","malt pepper"] },
  { navn: "Ris", ikon: "🍚", kat: "tørrvarer", alias: ["ris","basmati","jasminris","rundkornet ris","arborio","sushiris","uncle ben's","uncle bens"] },
  { navn: "Pasta", ikon: "🍝", kat: "tørrvarer", alias: ["pasta","spaghetti","fusilli","penne","rigatoni","tagliatelle","linguine","farfalle","lasagneplater"] },
  { navn: "Havregryn", ikon: "🌾", kat: "tørrvarer", alias: ["havregryn","store havregryn","fine havregryn","stavanger havregryn","quaker"] },
  { navn: "Müsli", ikon: "🌾", kat: "tørrvarer", alias: ["müsli","muesli","granola","birgit tengsareid","fitness cereals","jordnær müsli"] },
  { navn: "Cornflakes", ikon: "🌾", kat: "tørrvarer", alias: ["cornflakes","kellog's","kelloggs","corn flakes","frokostblanding"] },
  { navn: "Olje", ikon: "🫙", kat: "tørrvarer", alias: ["solsikkeolje","rapsolje","olje","vegetabilsk olje","frityrolje"] },
  { navn: "Olivenolje", ikon: "🫒", kat: "tørrvarer", alias: ["olivenolje","extra virgin","olivolje","olicana","filippo berio"] },
  { navn: "Ketchup", ikon: "🍅", kat: "tørrvarer", alias: ["ketchup","heinz","stabburet ketchup","tomatsketchup","organisk ketchup"] },
  { navn: "Majones", ikon: "🫙", kat: "tørrvarer", alias: ["majones","mills majones","hellmanns","lett majones","aioli","remoulade"] },
  { navn: "Sennep", ikon: "🫙", kat: "tørrvarer", alias: ["sennep","grov sennep","dijon","sterk sennep","honey mustard","maille"] },
  { navn: "Soyasaus", ikon: "🫙", kat: "tørrvarer", alias: ["soyasaus","soya","kikkoman","tamari","ketjap","dark soy"] },
  { navn: "Syltetøy", ikon: "🫙", kat: "tørrvarer", alias: ["syltetøy","jordbærsyltetøy","blåbærsyltetøy","bringebærsyltetøy","marmelade","jam"] },
  { navn: "Honning", ikon: "🍯", kat: "tørrvarer", alias: ["honning","blomsterhonning","lynghonning","akasiehonning","manuka"] },
  { navn: "Peanøttsmør", ikon: "🥜", kat: "tørrvarer", alias: ["peanøttsmør","nutella","mandelsmør","nøttesmør","skippy","jif"] },
  { navn: "Nutella", ikon: "🫙", kat: "tørrvarer", alias: ["nutella","sjokoladepålegg","nugatti","påleggssjokolade"] },
  { navn: "Tomatpuré", ikon: "🍅", kat: "tørrvarer", alias: ["tomatpuré","tomato paste","mutti","concentrato"] },
  { navn: "Hermetiske tomater", ikon: "🍅", kat: "tørrvarer", alias: ["hermetiske tomater","knuste tomater","tomater på boks","mutti polpa","chopped tomatoes"] },
  { navn: "Kokosmelk", ikon: "🥥", kat: "tørrvarer", alias: ["kokosmelk","coconut milk","flaske kokos","ayam","chaokoh"] },
  { navn: "Linser", ikon: "🫘", kat: "tørrvarer", alias: ["linser","røde linser","grønne linser","puy linser"] },
  { navn: "Kikerter", ikon: "🫘", kat: "tørrvarer", alias: ["kikerter","kikert","chickpeas","hvite bønner boks"] },
  { navn: "Bønner", ikon: "🫘", kat: "tørrvarer", alias: ["bønner","kidneybønner","svarte bønner","cannellini","hvite bønner"] },
  { navn: "Karri", ikon: "🌶️", kat: "tørrvarer", alias: ["karri","curry","garam masala","tikka masala","karripulver","mccormick"] },
  { navn: "Kanel", ikon: "🌶️", kat: "tørrvarer", alias: ["kanel","malt kanel","kanelstang","ceylon kanel"] },
  { navn: "Paprikakrydder", ikon: "🌶️", kat: "tørrvarer", alias: ["paprika krydder","paprikapulver","røkt paprika","søt paprika","smoked paprika"] },
  { navn: "Oregano", ikon: "🌿", kat: "tørrvarer", alias: ["oregano","tørket oregano","italiensk krydder"] },
  { navn: "Basilikum", ikon: "🌿", kat: "tørrvarer", alias: ["basilikum","tørket basilikum","fersk basilikum"] },
  { navn: "Timian", ikon: "🌿", kat: "tørrvarer", alias: ["timian","tørket timian"] },
  { navn: "Rosmarin", ikon: "🌿", kat: "tørrvarer", alias: ["rosmarin","tørket rosmarin"] },
  { navn: "Cumin", ikon: "🌿", kat: "tørrvarer", alias: ["cumin","spiskummen","kummin","malt cumin"] },
  { navn: "Chili", ikon: "🌶️", kat: "tørrvarer", alias: ["chili","chilipulver","cayenne","chiliflak","tørket chili","chili flakes"] },
  { navn: "Vaniljesukker", ikon: "🌿", kat: "tørrvarer", alias: ["vaniljesukker","vaniljepulver","bourbon vanilje","vaniljestang"] },
  { navn: "Bakepulver", ikon: "🫙", kat: "tørrvarer", alias: ["bakepulver","baking powder","natron","hjortetakksalt"] },
  { navn: "Gjær", ikon: "🫙", kat: "tørrvarer", alias: ["gjær","tørrgjær","fersk gjær","pizzagjær"] },
  { navn: "Maisenna", ikon: "🫙", kat: "tørrvarer", alias: ["maisenna","maisstivelse","potetmel","gustin"] },
  { navn: "Buljong", ikon: "🫙", kat: "tørrvarer", alias: ["buljong","hönsbuljong","kjøttbuljong","fond","grønnsaksbuljong","kraft"] },
  { navn: "Nudler", ikon: "🍜", kat: "tørrvarer", alias: ["nudler","ramen","udon","soba","risnudler","glassnudler","indomie"] },
  { navn: "Couscous", ikon: "🌾", kat: "tørrvarer", alias: ["couscous","bulgur","quinoa"] },
  { navn: "Quinoa", ikon: "🌾", kat: "tørrvarer", alias: ["quinoa","hvit quinoa","rød quinoa","tri-color quinoa"] },
  { navn: "Eddik", ikon: "🫙", kat: "tørrvarer", alias: ["eddik","hvitvinseddik","rødvinseddik","balsamicoeddik","epleeddik","riseddik"] },
  { navn: "Tabasco", ikon: "🌶️", kat: "tørrvarer", alias: ["tabasco","sriracha","chilisaus","sweet chili","frank's hot sauce"] },
  { navn: "Worcestershiresaus", ikon: "🫙", kat: "tørrvarer", alias: ["worcestershire","worcestershiresaus","lea perrins"] },
  { navn: "Pesto", ikon: "🫙", kat: "tørrvarer", alias: ["pesto","basilikapesto","rød pesto","barilla pesto","sacla"] },
  { navn: "Pastasaus", ikon: "🍅", kat: "tørrvarer", alias: ["pastasaus","bolognese saus","arrabiata","carbonara saus","ragu"] },
  { navn: "Havresaus", ikon: "🫙", kat: "tørrvarer", alias: ["brunsaus","sausepulver","fond du chef","demi glace"] },
  { navn: "Risotto", ikon: "🍚", kat: "tørrvarer", alias: ["risottoris","arborio","carnaroli"] },
  { navn: "Popcorn", ikon: "🍿", kat: "tørrvarer", alias: ["popcorn","micropopcorn","popcornkjerner"] },

  // ─── FRYSEVARER ───────────────────────────────────────────────────────────
  { navn: "Frossen pizza", ikon: "🍕", kat: "frysevarer", alias: ["pizza","grandiosa","fryst pizza","toro pizza","big one","frossen pizza","stabburet pizza"] },
  { navn: "Fiskepinner", ikon: "🐟", kat: "frysevarer", alias: ["fiskepinner","findus fiskepinner","gorton's","frozen fish fingers"] },
  { navn: "Pommes frites", ikon: "🍟", kat: "frysevarer", alias: ["pommes frites","pommes","frites","mccain","frionor pommes"] },
  { navn: "Is", ikon: "🍦", kat: "frysevarer", alias: ["is","iskrem","is boks","diplom is","hennig olsen","ben & jerry's","häagen dazs","magnum"] },
  { navn: "Frosne erter", ikon: "🫛", kat: "frysevarer", alias: ["frosne erter","fryste erter","frossen erter"] },
  { navn: "Frosne bær", ikon: "🍓", kat: "frysevarer", alias: ["frosne bær","fryste jordbær","frosne blåbær","frozen berries","fryst frukt"] },
  { navn: "Frossen spinat", ikon: "🥬", kat: "frysevarer", alias: ["frossen spinat","fryst spinat","findus spinat"] },
  { navn: "Frossen fisk", ikon: "🐟", kat: "frysevarer", alias: ["frossen laks","frossen torsk","frossen sei","frossen fisk","frionor fisk"] },
  { navn: "Frossen grønnsaksblanding", ikon: "🥦", kat: "frysevarer", alias: ["grønnsaksblanding","frossen grønnsak","findus grønnsaker","wok grønnsaker"] },
  { navn: "Frossen kylling", ikon: "🍗", kat: "frysevarer", alias: ["frossen kylling","kyllingnuggets","chicken nuggets","fryst kylling"] },
  { navn: "Frossen burger", ikon: "🍔", kat: "frysevarer", alias: ["frossen burger","hamburgere","beef burger","chicken burger"] },
  { navn: "Iskaffe", ikon: "☕", kat: "frysevarer", alias: ["iskaffe","frappuccino","nescafe frappé"] },
  { navn: "Frosne vafler", ikon: "🧇", kat: "frysevarer", alias: ["frosne vafler","fryst vafler"] },

  // ─── DRIKKE ───────────────────────────────────────────────────────────────
  { navn: "Kaffe", ikon: "☕", kat: "drikke", alias: ["kaffe","friele","jacobsens","evergood","nespresso","kaffekapsler","filterkaffe","espresso","bryggkaffe"] },
  { navn: "Te", ikon: "🍵", kat: "drikke", alias: ["te","grønn te","sort te","english breakfast","earl grey","pepperminte","ingefærte","lipton","twinings"] },
  { navn: "Appelsinjuice", ikon: "🍊", kat: "drikke", alias: ["appelsinjuice","juice","tropicana","tine juice","rynkeby","pressafrukt","fersk juice"] },
  { navn: "Eplejuice", ikon: "🍎", kat: "drikke", alias: ["eplejuice","apple juice","eplemost"] },
  { navn: "Saft", ikon: "🧃", kat: "drikke", alias: ["saft","appelsinbrus","helsaft","fruktsaft","ribena","squash"] },
  { navn: "Mineralvann", ikon: "💧", kat: "drikke", alias: ["mineralvann","vann","farris","imsdal","isklar","perrier","san pellegrino","spa"] },
  { navn: "Cola", ikon: "🥤", kat: "drikke", alias: ["cola","coca-cola","pepsi","cola zero","pepsi max","diet coke"] },
  { navn: "Solo", ikon: "🥤", kat: "drikke", alias: ["solo","fanta","sprite","7up","mirinda","brus"] },
  { navn: "Energidrikk", ikon: "⚡", kat: "drikke", alias: ["red bull","monster","battery","redbull","energidrikk","burn"] },
  { navn: "Øl", ikon: "🍺", kat: "drikke", alias: ["øl","hansa","ringnes","corona","heineken","budweiser","tuborg","pilsner","ipa","pale ale"] },
  { navn: "Hvitvin", ikon: "🍷", kat: "drikke", alias: ["hvitvin","chardonnay","sauvignon blanc","pinot grigio","riesling","white wine"] },
  { navn: "Rødvin", ikon: "🍷", kat: "drikke", alias: ["rødvin","cabernet","merlot","syrah","primitivo","chianti","red wine"] },
  { navn: "Rosé", ikon: "🍷", kat: "drikke", alias: ["rosé","rose vin","rosévine","provence rosé"] },
  { navn: "Sider", ikon: "🍺", kat: "drikke", alias: ["sider","eple sider","strongbow","magners"] },
  { navn: "Sportsdrink", ikon: "💧", kat: "drikke", alias: ["sportsdrink","gatorade","powerade","isostar","vitaminwater"] },
  { navn: "Kakaopulver", ikon: "☕", kat: "drikke", alias: ["kakao","kakaopulver","nesquik","cocio","varm sjokolade","milo"] },
  { navn: "Nescafé", ikon: "☕", kat: "drikke", alias: ["nescafé","instant kaffe","nescafe gold","jacobs velvet"] },
  { navn: "Proteinshake", ikon: "💪", kat: "drikke", alias: ["proteinshake","protein drink","whey","myseprotein","gainomax"] },
  { navn: "Smoothie", ikon: "🥤", kat: "drikke", alias: ["smoothie","innocent smoothie","bare smoothie"] },

  // ─── SNACKS & GODIS ───────────────────────────────────────────────────────
  { navn: "Melkesjokolade", ikon: "🍫", kat: "snacks", alias: ["melkesjokolade","freia melkesjokolade","kvikk lunsj","non stop","smash","toblerone","milka","lindt"] },
  { navn: "Mørk sjokolade", ikon: "🍫", kat: "snacks", alias: ["mørk sjokolade","70%","dark chocolate","excellence","freia mørk"] },
  { navn: "Chips", ikon: "🥔", kat: "snacks", alias: ["chips","originalchips","salt chips","lay's","lays","maarud","sour cream","paprikachips"] },
  { navn: "Popcorn", ikon: "🍿", kat: "snacks", alias: ["popcorn","salt popcorn","smør popcorn","micropopcorn"] },
  { navn: "Nøtter", ikon: "🥜", kat: "snacks", alias: ["nøtter","cashew","mandler","valnøtter","peanøtter","pistasj","macadamia","blandede nøtter"] },
  { navn: "Kjeks", ikon: "🍪", kat: "snacks", alias: ["kjeks","digestive","hobnobs","oreo","bourbon","marie","rich tea","wasa"] },
  { navn: "Godteri", ikon: "🍬", kat: "snacks", alias: ["godteri","vingummi","lakrisbåter","seierstre","skumbananer","haribo","trolli"] },
  { navn: "Lakris", ikon: "🍬", kat: "snacks", alias: ["lakris","salzlakritz","skipper's pipes","heksehyl"] },
  { navn: "Marshmallows", ikon: "🍬", kat: "snacks", alias: ["marshmallows","skumgodis","mello yello"] },
  { navn: "Rosiner", ikon: "🍇", kat: "snacks", alias: ["rosiner","sultanrosiner","tørkede druer","sun-maid"] },
  { navn: "Tørkede frukter", ikon: "🍑", kat: "snacks", alias: ["tørkede frukter","tørket mango","aprikoser","dadler","sviskos","fikener"] },
  { navn: "Havrebar", ikon: "🌾", kat: "snacks", alias: ["havrebar","muslibar","nakd bar","rxbar","kind bar","trek bar"] },
  { navn: "Proteinbar", ikon: "💪", kat: "snacks", alias: ["proteinbar","protein bar","quest bar","oatein"] },
  { navn: "Crackere", ikon: "🫓", kat: "snacks", alias: ["crackere","vinta cracker","ritz","triscuit","jacob's cream crackers"] },
  { navn: "Potetgull", ikon: "🥔", kat: "snacks", alias: ["potetgull","maarud potetgull","kettle chips","pringles"] },
  { navn: "Nachos", ikon: "🌮", kat: "snacks", alias: ["nachos","tortillachips","doritos","salsa","dipchips"] },
  { navn: "Ostepop", ikon: "🧀", kat: "snacks", alias: ["ostepop","cheetos","toffifee"] },

  // ─── HYGIENE & RENGJØRING ─────────────────────────────────────────────────
  { navn: "Toalettpapir", ikon: "🧻", kat: "hygiene", alias: ["toalettpapir","wc papir","toiletpapir","edet","lambi","tork","lotus","plenty"] },
  { navn: "Kjøkkenpapir", ikon: "🧻", kat: "hygiene", alias: ["kjøkkenpapir","tørkepapir","husholdningspapir","bounty","plenty kjøkken"] },
  { navn: "Tannkrem", ikon: "🪥", kat: "hygiene", alias: ["tannkrem","colgate","sensodyne","oral-b","elmex","pepsodent"] },
  { navn: "Tannbørste", ikon: "🪥", kat: "hygiene", alias: ["tannbørste","elektrisk tannbørste","oral b tannbørste","colgate tannbørste"] },
  { navn: "Sjampo", ikon: "🧴", kat: "hygiene", alias: ["sjampo","shampoo","head & shoulders","pantene","elvive","dove shampoo","sunsilk"] },
  { navn: "Balsam", ikon: "🧴", kat: "hygiene", alias: ["balsam","conditioner","pantene balsam","dove conditioner"] },
  { navn: "Dusjsåpe", ikon: "🧴", kat: "hygiene", alias: ["dusjsåpe","shower gel","dove dusjsåpe","palmolive","radox","lynx"] },
  { navn: "Såpe", ikon: "🧼", kat: "hygiene", alias: ["såpe","flytende såpe","håndsåpe","dove såpe","lux","palmolive såpe"] },
  { navn: "Deodorant", ikon: "🧴", kat: "hygiene", alias: ["deodorant","antiperspirant","rexona","sure","axe","nivea deodorant","mitchum"] },
  { navn: "Barberhøvel", ikon: "🪒", kat: "hygiene", alias: ["barberhøvel","gillette","venus","razors","bic razors"] },
  { navn: "Barberskum", ikon: "🧴", kat: "hygiene", alias: ["barberskum","shaving cream","gillette gel","nivea barbering"] },
  { navn: "Håndkrem", ikon: "🧴", kat: "hygiene", alias: ["håndkrem","body lotion","neutrogena","o'keeffe's","cien"] },
  { navn: "Fuktighetskrem", ikon: "🧴", kat: "hygiene", alias: ["fuktighetskrem","ansiktskrem","nivea","olay","garnier"] },
  { navn: "Solkrem", ikon: "🧴", kat: "hygiene", alias: ["solkrem","solfaktor","spf","sun cream","sollotion"] },
  { navn: "Oppvaskmiddel", ikon: "🫧", kat: "hygiene", alias: ["oppvaskmiddel","fairy","sun oppvask","palmolive oppvask","prima oppvask"] },
  { navn: "Oppvasktabletter", ikon: "🫧", kat: "hygiene", alias: ["oppvasktabletter","finish","somat","sun tabletter","cascade"] },
  { navn: "Vaskemiddel", ikon: "🫧", kat: "hygiene", alias: ["vaskemiddel","ariel","persil","tide","omo","bio vask","color vask"] },
  { navn: "Tøymykner", ikon: "🫧", kat: "hygiene", alias: ["tøymykner","skyllemiddel","lenor","comfort","snuggle"] },
  { navn: "Rens", ikon: "🫧", kat: "hygiene", alias: ["rengjøringsspray","ajax","jif","mr. muscle","cif","antibac"] },
  { navn: "Antibac", ikon: "🫧", kat: "hygiene", alias: ["antibac","desinfeksjon","håndsprit","hånddesinfeksjon"] },
  { navn: "Søppelposer", ikon: "🗑️", kat: "hygiene", alias: ["søppelposer","bosposer","avfallsposer","duni poser"] },
  { navn: "Aluminiumsfolie", ikon: "📦", kat: "hygiene", alias: ["aluminiumsfolie","alu folie","staniol","reynolds wrap"] },
  { navn: "Plastfolie", ikon: "📦", kat: "hygiene", alias: ["plastfolie","cling film","glad wrap","saranwrap"] },
  { navn: "Bleier", ikon: "👶", kat: "hygiene", alias: ["bleier","pampers","huggies","libero","drypers"] },
  { navn: "Våtservietter", ikon: "🧻", kat: "hygiene", alias: ["våtservietter","babywipes","pampers wipes","huggies wipes"] },
  { navn: "Bind", ikon: "🩹", kat: "hygiene", alias: ["bind","tamponger","truseinnlegg","always","libresse","stayfree"] },
  { navn: "Stikkpiller", ikon: "💊", kat: "hygiene", alias: ["paracet","ibuprofen","aspirin","smertestillende"] },
  { navn: "Servietter", ikon: "🧻", kat: "hygiene", alias: ["servietter","papirservietter","middagsservietter","duni"] },
  { navn: "Zip-poser", ikon: "📦", kat: "hygiene", alias: ["zip-poser","fryseposer","glad zip","minigrip"] },
  { navn: "Strikk", ikon: "📦", kat: "hygiene", alias: ["strikk","gummistrikk"] },

  // ─── ANNET ────────────────────────────────────────────────────────────────
  { navn: "Hundemat", ikon: "🐕", kat: "annet", alias: ["hundemat","pedigree","royal canin","hills","cesar","purina dog"] },
  { navn: "Kattemat", ikon: "🐈", kat: "annet", alias: ["kattemat","felix","whiskas","royal canin katt","purina cat"] },
  { navn: "Blomster", ikon: "💐", kat: "annet", alias: ["blomster","bukett","tulipaner","roser","liljer"] },
  { navn: "Stearinlys", ikon: "🕯️", kat: "annet", alias: ["stearinlys","bloklys","lys","fyrfadslys","telys"] },
  { navn: "Batterier", ikon: "🔋", kat: "annet", alias: ["batterier","aa batterier","aaa batterier","duracell","energizer"] },
  { navn: "Lyspære", ikon: "💡", kat: "annet", alias: ["lyspære","led pære","philips led","ikea led"] },
  { navn: "Tapas", ikon: "🫒", kat: "annet", alias: ["oliven","antipasti","artisjokkhjerte","pimientos","kapers"] },
  { navn: "Sushi", ikon: "🍣", kat: "annet", alias: ["sushi","nori","sushiris","wasabi","soyasaus sushi","ingefær sushi"] },
  // ─── MEIERI EKSTRA ────────────────────────────────────────────────────────
  { navn: "Laktefri fløte", ikon: "🫙", kat: "meieri", alias: ["laktosefri fløte","lactofri fløte","arla lactofree"] },
  { navn: "Kefir", ikon: "🥛", kat: "meieri", alias: ["kefir","biola kefir","tine kefir"] },
  { navn: "Kvarg", ikon: "🍶", kat: "meieri", alias: ["kvarg","kvark","skyr kvarg","milram kvarg"] },
  { navn: "Smøreost med urter", ikon: "🧀", kat: "meieri", alias: ["smøreost urter","herb cream cheese","philadelphia urter"] },
  { navn: "Hvitost skivet", ikon: "🧀", kat: "meieri", alias: ["hvitost skivet","norvegia skivet","jarlsberg skivet","gouda skivet"] },
  { navn: "Revet ost", ikon: "🧀", kat: "meieri", alias: ["revet ost","revet norvegia","revet mozarella","grateng ost","pizza ost"] },
  { navn: "Brie", ikon: "🧀", kat: "meieri", alias: ["brie","camembert","president brie","castello brie"] },
  { navn: "Gorgonzola", ikon: "🧀", kat: "meieri", alias: ["gorgonzola","blåmuggost","roquefort","stilton"] },
  { navn: "Manchego", ikon: "🧀", kat: "meieri", alias: ["manchego","spansk ost","pecorino"] },
  { navn: "Cheddar", ikon: "🧀", kat: "meieri", alias: ["cheddar","mature cheddar","mild cheddar","cathedral city"] },
  { navn: "Ricotta", ikon: "🧀", kat: "meieri", alias: ["ricotta","ricottaost"] },
  { navn: "Mascarpone", ikon: "🧀", kat: "meieri", alias: ["mascarpone","tiramisu ost"] },
  { navn: "Syrnet melk", ikon: "🥛", kat: "meieri", alias: ["surmelk","filmjölk","A-fil"] },
  { navn: "Havredrikkk", ikon: "🥛", kat: "meieri", alias: ["oatly havre","oat drink","havredrikk","oatly barista"] },
  { navn: "Mandelmelk", ikon: "🥛", kat: "meieri", alias: ["mandelmelk","almond milk","alpro mandel"] },
  { navn: "Soyamelk", ikon: "🥛", kat: "meieri", alias: ["soyamelk","soya drink","alpro soya","alpro soja"] },
  { navn: "Kokosdrikk", ikon: "🥥", kat: "meieri", alias: ["kokosdrikk","kokos melk drikke","alpro kokos"] },

  // ─── BRØD EKSTRA ──────────────────────────────────────────────────────────
  { navn: "Foccacia", ikon: "🍞", kat: "brod-bakeri", alias: ["focaccia","foccacia","italiensk flatbrød"] },
  { navn: "Naan", ikon: "🫓", kat: "brod-bakeri", alias: ["naan","naanbrød","indisk brød","garlic naan"] },
  { navn: "Chapati", ikon: "🫓", kat: "brod-bakeri", alias: ["chapati","roti","indisk chapati"] },
  { navn: "Rugbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["rugbrød","dansk rugbrød","surdeigsrugbrød"] },
  { navn: "Speltbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["speltbrød","spelt","dinkelbrød"] },
  { navn: "Glutenfritt brød", ikon: "🍞", kat: "brod-bakeri", alias: ["glutenfritt brød","schar brød","schär","fria brød"] },
  { navn: "Pão de queijo", ikon: "🧀", kat: "brod-bakeri", alias: ["osteboller","osteflatbrød"] },
  { navn: "Waffelrør", ikon: "🍦", kat: "brod-bakeri", alias: ["waffelrør","iskremrør","vaffelkjeks"] },
  { navn: "Müslibrød", ikon: "🍞", kat: "brod-bakeri", alias: ["müslibrød","mueslibrød","havrelandbrød"] },
  { navn: "Proteinbrød", ikon: "🍞", kat: "brod-bakeri", alias: ["proteinbrød","low carb brød","lavkarbo brød"] },

  // ─── FRUKT & GRØNT EKSTRA ─────────────────────────────────────────────────
  { navn: "Ruccola", ikon: "🥬", kat: "frukt-gront", alias: ["ruccola","rucola","raketsalat","wild rocket"] },
  { navn: "Friske urter", ikon: "🌿", kat: "frukt-gront", alias: ["frisk basilikum","fersk koriander","fersk persille","fersk dill","fersk timian","friske urter"] },
  { navn: "Koriander", ikon: "🌿", kat: "frukt-gront", alias: ["koriander","fersk koriander","coriander"] },
  { navn: "Persille", ikon: "🌿", kat: "frukt-gront", alias: ["persille","fersk persille","kruspersille","bladpersille"] },
  { navn: "Dill", ikon: "🌿", kat: "frukt-gront", alias: ["dill","fersk dill"] },
  { navn: "Mynte", ikon: "🌿", kat: "frukt-gront", alias: ["mynte","fersk mynte","mint"] },
  { navn: "Chilli", ikon: "🌶️", kat: "frukt-gront", alias: ["fersk chilli","rød chilli","grønn chilli","bird's eye"] },
  { navn: "Brokkolini", ikon: "🥦", kat: "frukt-gront", alias: ["brokkolini","tenderstem","babyshoots"] },
  { navn: "Spagettisquash", ikon: "🥒", kat: "frukt-gront", alias: ["spagettisquash","butternut squash","gresskar"] },
  { navn: "Gresskar", ikon: "🎃", kat: "frukt-gront", alias: ["gresskar","pumpkin","butternut"] },
  { navn: "Artisjokkhjerte", ikon: "🌿", kat: "frukt-gront", alias: ["artisjokk","artisjokkhjerte","carciofi"] },
  { navn: "Pak choi", ikon: "🥬", kat: "frukt-gront", alias: ["pak choi","bok choy","kinesisk kål"] },
  { navn: "Yam", ikon: "🍠", kat: "frukt-gront", alias: ["yam","yamrot","taro"] },
  { navn: "Papaya", ikon: "🍑", kat: "frukt-gront", alias: ["papaya","fersk papaya"] },
  { navn: "Kokosnøtt", ikon: "🥥", kat: "frukt-gront", alias: ["kokosnøtt","fersk kokos","kokos"] },
  { navn: "Granateple", ikon: "🍎", kat: "frukt-gront", alias: ["granateple","pomegranate"] },
  { navn: "Passjonsfrukt", ikon: "🍑", kat: "frukt-gront", alias: ["passjonsfrukt","passion fruit","maracuja"] },
  { navn: "Litchi", ikon: "🍑", kat: "frukt-gront", alias: ["litchi","lychee","lichi"] },
  { navn: "Fiken", ikon: "🍑", kat: "frukt-gront", alias: ["fersk fiken","fiken","fig"] },
  { navn: "Rødbeter", ikon: "🫛", kat: "frukt-gront", alias: ["rødbeter","rødbete","beteroter","vakuumrødbeter"] },
  { navn: "Pastinakk", ikon: "🥕", kat: "frukt-gront", alias: ["pastinakk","parsnip"] },
  { navn: "Kålrabi", ikon: "🥬", kat: "frukt-gront", alias: ["kålrabi","kohlrabi"] },
  { navn: "Jordskokk", ikon: "🥔", kat: "frukt-gront", alias: ["jordskokk","jerusalem artichoke"] },
  { navn: "Bambusskudd", ikon: "🌿", kat: "frukt-gront", alias: ["bambusskudd","bamboo shoots","bamboo"] },
  { navn: "Bønnefrø", ikon: "🫘", kat: "frukt-gront", alias: ["spirer","bønnespirer","sojaspirer","alfalfaspirer"] },

  // ─── KJØTT & FISK EKSTRA ──────────────────────────────────────────────────
  { navn: "Hamburger", ikon: "🍔", kat: "kjott-fisk", alias: ["hamburgerpatties","beef patties","hamburgere","biff burger"] },
  { navn: "Svinerib", ikon: "🥩", kat: "kjott-fisk", alias: ["ribbe","julerib","svineribbe","ribbestriper"] },
  { navn: "Oksehale", ikon: "🥩", kat: "kjott-fisk", alias: ["oksehale","oxtail","oksehalegryte"] },
  { navn: "Hjortekjøtt", ikon: "🦌", kat: "kjott-fisk", alias: ["hjort","reinsdyr","elgkjøtt","vilt","viltkjøtt"] },
  { navn: "And", ikon: "🦆", kat: "kjott-fisk", alias: ["and","andebryst","andekjøtt","confit de canard"] },
  { navn: "Kalvekjøtt", ikon: "🥩", kat: "kjott-fisk", alias: ["kalv","kalvekjøtt","kalvefilet","wiener schnitzel"] },
  { navn: "Kalkun", ikon: "🦃", kat: "kjott-fisk", alias: ["kalkun","kalkunfilet","kalkundeig","turkey"] },
  { navn: "Spekeskinke", ikon: "🍖", kat: "kjott-fisk", alias: ["spekeskinke","serrano","prosciutto crudo","fenalår","coppa"] },
  { navn: "Leverpostei", ikon: "🫙", kat: "kjott-fisk", alias: ["leverpostei","stabbur-lever","gilde leverpostei"] },
  { navn: "Rullepølse", ikon: "🍖", kat: "kjott-fisk", alias: ["rullepølse","medvurst","cervelat","mortadella"] },
  { navn: "Blodpudding", ikon: "🍖", kat: "kjott-fisk", alias: ["blodpudding","blodpølse","blodklubb"] },
  { navn: "Crabsticks", ikon: "🦀", kat: "kjott-fisk", alias: ["crabsticks","krabbesticks","surimi"] },
  { navn: "Blåskjell", ikon: "🦪", kat: "kjott-fisk", alias: ["blåskjell","mussels","blåskjell fersk"] },
  { navn: "Kamskjell", ikon: "🦪", kat: "kjott-fisk", alias: ["kamskjell","scallops"] },
  { navn: "Blekksprut", ikon: "🦑", kat: "kjott-fisk", alias: ["blekksprut","squid","calamari"] },
  { navn: "Sjøkreps", ikon: "🦞", kat: "kjott-fisk", alias: ["sjøkreps","hummer","lobster","langoustine"] },
  { navn: "Ansjos", ikon: "🐟", kat: "kjott-fisk", alias: ["ansjos","ansjosfileter","sardeller"] },
  { navn: "Sild", ikon: "🐟", kat: "kjott-fisk", alias: ["sild","matjes","sildesalat","krydret sild","glassmestersild"] },
  { navn: "Abbor", ikon: "🐟", kat: "kjott-fisk", alias: ["abbor","ørretabbor","røye"] },
  { navn: "Kveite", ikon: "🐟", kat: "kjott-fisk", alias: ["kveite","helleflyndre","kveitefile"] },

  // ─── TØRRVARER EKSTRA ─────────────────────────────────────────────────────
  { navn: "Durumhvete", ikon: "🌾", kat: "tørrvarer", alias: ["durummel","semolina","durumhvete"] },
  { navn: "Speltmel", ikon: "🌾", kat: "tørrvarer", alias: ["speltmel","dinkelmel","spelt hvetemel"] },
  { navn: "Mandelmel", ikon: "🌾", kat: "tørrvarer", alias: ["mandelmel","almond flour","malt mandel"] },
  { navn: "Kokosfett", ikon: "🥥", kat: "tørrvarer", alias: ["kokosolje","kokos olje","coconut oil","kokosfett"] },
  { navn: "Sesamolje", ikon: "🫙", kat: "tørrvarer", alias: ["sesamolje","sesame oil","ristet sesamolje"] },
  { navn: "Fiskesaus", ikon: "🫙", kat: "tørrvarer", alias: ["fiskesaus","fish sauce","nam pla","nuoc mam"] },
  { navn: "Østerssaus", ikon: "🫙", kat: "tørrvarer", alias: ["østerssaus","oyster sauce","hoisin"] },
  { navn: "Miso", ikon: "🫙", kat: "tørrvarer", alias: ["miso","misopasta","hvit miso","rød miso"] },
  { navn: "Tahini", ikon: "🫙", kat: "tørrvarer", alias: ["tahini","sesamsmør","sesampasta"] },
  { navn: "Hummus", ikon: "🫙", kat: "tørrvarer", alias: ["hummus","kikertpuré"] },
  { navn: "Kapers", ikon: "🫙", kat: "tørrvarer", alias: ["kapers","capers","kapersbær"] },
  { navn: "Soltørkede tomater", ikon: "🍅", kat: "tørrvarer", alias: ["soltørkede tomater","sun dried tomatoes","tørkede tomater i olje"] },
  { navn: "Artisjokkhjerte boks", ikon: "🫙", kat: "tørrvarer", alias: ["artisjokk boks","artisjokkhjerte hermetisk"] },
  { navn: "Bambusskudd boks", ikon: "🫙", kat: "tørrvarer", alias: ["bambusskudd boks","bamboo shoots boks"] },
  { navn: "Kokosflis", ikon: "🥥", kat: "tørrvarer", alias: ["kokosflis","revet kokos","kokosflak","desiccated coconut"] },
  { navn: "Sirupz", ikon: "🍯", kat: "tørrvarer", alias: ["sirup","lys sirup","mørk sirup","lønnesirup","agave"] },
  { navn: "Potetmos", ikon: "🥔", kat: "tørrvarer", alias: ["potetmos","potetmospulver","toro potetmos","stavanger potetmos"] },
  { navn: "Suppe pose", ikon: "🍲", kat: "tørrvarer", alias: ["toro suppe","knorr suppe","suppepulver","tomatsuppe","grønnsakssuppe"] },
  { navn: "Sauspulver", ikon: "🫙", kat: "tørrvarer", alias: ["sauspulver","brunsaus pose","hvit saus","bechamel pulver","fondor"] },
  { navn: "Majsgryn", ikon: "🌾", kat: "tørrvarer", alias: ["polenta","majsgryn","cornmeal"] },
  { navn: "Vermicelli", ikon: "🍜", kat: "tørrvarer", alias: ["vermicelli","tynn pasta","angel hair","capellini"] },
  { navn: "Panko", ikon: "🌾", kat: "tørrvarer", alias: ["panko","brødsmuler","rasps","strøbrød","hermetisk"] },

  // ─── DRIKKE EKSTRA ────────────────────────────────────────────────────────
  { navn: "Prosecco", ikon: "🥂", kat: "drikke", alias: ["prosecco","mionetto","cava","champagne","sparkling wine","musserende vin"] },
  { navn: "Gin", ikon: "🍸", kat: "drikke", alias: ["gin","hendricks","tanqueray","bombay sapphire","gordons"] },
  { navn: "Whisky", ikon: "🥃", kat: "drikke", alias: ["whisky","whiskey","bourbon","scotch","jameson","jack daniels"] },
  { navn: "Vodka", ikon: "🍸", kat: "drikke", alias: ["vodka","absolut","smirnoff","grey goose"] },
  { navn: "Rom", ikon: "🍸", kat: "drikke", alias: ["rom","mørk rom","lys rom","bacardi","havana club"] },
  { navn: "Likør", ikon: "🍸", kat: "drikke", alias: ["baileys","kahlua","cointreau","amaretto","likør"] },
  { navn: "Sprit", ikon: "🍸", kat: "drikke", alias: ["aquavit","linie aquavit","absolut vodka"] },
  { navn: "Blandingsdrikk", ikon: "🥤", kat: "drikke", alias: ["ready to drink","rtd","gin tonic boks","smirnoff ice"] },
  { navn: "Tonic", ikon: "🥤", kat: "drikke", alias: ["tonic water","fever tree","schweppes tonic","indian tonic"] },
  { navn: "Bitter lemon", ikon: "🍋", kat: "drikke", alias: ["bitter lemon","schweppes bitter","ginger ale","ginger beer"] },
  { navn: "Kokosvann", ikon: "🥥", kat: "drikke", alias: ["kokosvann","coconut water","vita coco"] },
  { navn: "Kombucha", ikon: "🍵", kat: "drikke", alias: ["kombucha","raw tea","GT's kombucha"] },
  { navn: "Kefirdrikk", ikon: "🥛", kat: "drikke", alias: ["kefirdrikk","drinking kefir","biola drikk"] },
  { navn: "Matcha", ikon: "🍵", kat: "drikke", alias: ["matcha","matchapulver","matcha latte"] },

  // ─── SNACKS EKSTRA ────────────────────────────────────────────────────────
  { navn: "Seigmenn", ikon: "🍬", kat: "snacks", alias: ["seigmenn","gummibærer","haribo goldbears","sour worms"] },
  { navn: "Karameller", ikon: "🍬", kat: "snacks", alias: ["karameller","toffee","karamell","werther's original","smil","stratos"] },
  { navn: "Drops", ikon: "🍬", kat: "snacks", alias: ["drops","halls","fisherman's friend","mintkuler"] },
  { navn: "Tyggegummi", ikon: "🍬", kat: "snacks", alias: ["tyggegummi","extra","orbit","trident","hubba bubba"] },
  { navn: "Sjokoladeplate", ikon: "🍫", kat: "snacks", alias: ["stratos","daim","twist","plopp","daimkake"] },
  { navn: "Boble wrap", ikon: "🍫", kat: "snacks", alias: ["aero","bubbly","wispa"] },
  { navn: "Sjokoladebar", ikon: "🍫", kat: "snacks", alias: ["twix","kit kat","snickers","mars","bounty","lion bar"] },
  { navn: "Oliven", ikon: "🫒", kat: "snacks", alias: ["oliven","grønne oliven","svarte oliven","stuffed olives","kalamata"] },
  { navn: "Hummus pakke", ikon: "🫘", kat: "snacks", alias: ["hummus ferdig","sabra hummus","hummus med paprika"] },
  { navn: "Proteinchips", ikon: "💪", kat: "snacks", alias: ["proteinchips","no pain","lentil chips"] },
  { navn: "Riskaker", ikon: "🌾", kat: "snacks", alias: ["riskaker","riscrispis","rice cakes","kallo"] },
  { navn: "Maissnacks", ikon: "🌽", kat: "snacks", alias: ["maissnacks","wotsits","twisties"] },
  { navn: "Tørkede frukter pakke", ikon: "🍑", kat: "snacks", alias: ["dried mango","tørket ananas","tørket banan"] },

  // ─── HYGIENE EKSTRA ───────────────────────────────────────────────────────
  { navn: "Intimvask", ikon: "🧴", kat: "hygiene", alias: ["intimvask","femfresh","lactacyd"] },
  { navn: "Q-tips", ikon: "🩹", kat: "hygiene", alias: ["q-tips","bomullspinner","ørerengjøring"] },
  { navn: "Plaster", ikon: "🩹", kat: "hygiene", alias: ["plaster","band-aid","elastoplast","hansaplast"] },
  { navn: "Hostesaft", ikon: "🍯", kat: "hygiene", alias: ["hostesaft","flensmiddel","prospan","cosedal"] },
  { navn: "Nesespray", ikon: "💊", kat: "hygiene", alias: ["nesespray","otrivin","rhinomer","nasonex"] },
  { navn: "Øyedråper", ikon: "💊", kat: "hygiene", alias: ["øyedråper","visine","systane","optrex"] },
  { navn: "Vitaminer", ikon: "💊", kat: "hygiene", alias: ["multivitamin","vitaminc","vitamin d","omega 3","tran","vitalipid"] },
  { navn: "Kondomer", ikon: "💊", kat: "hygiene", alias: ["kondom","durex","rfsu","trojan"] },
  { navn: "Barberskum dame", ikon: "🧴", kat: "hygiene", alias: ["barbergelé","epilering","veet","nair"] },
  { navn: "Hårfarge", ikon: "🎨", kat: "hygiene", alias: ["hårfarge","hårbleking","nice n easy","schwarzkopf"] },
  { navn: "Neglefjerner", ikon: "💅", kat: "hygiene", alias: ["neglelakkfjerner","aceton","nail polish remover"] },
  { navn: "Solbriller", ikon: "🕶️", kat: "hygiene", alias: [] },
  { navn: "Kontaktlinser", ikon: "👁️", kat: "hygiene", alias: ["kontaktlinser","dagslins","monthly lenses","acuvue"] },
  { navn: "Elektrisk tannbørste refill", ikon: "🪥", kat: "hygiene", alias: ["tannbørstehoder","oral-b refill","braun refill"] },
  { navn: "Munnskyll", ikon: "🫧", kat: "hygiene", alias: ["munnskyll","listerine","corsodyl","colgate plax"] },
  { navn: "Tanntråd", ikon: "🪥", kat: "hygiene", alias: ["tanntråd","floss","oral-b floss","reach floss"] },

  // ─── MAT & FERDIGMAT ──────────────────────────────────────────────────────
  { navn: "Lasagne", ikon: "🍝", kat: "frysevarer", alias: ["lasagne ferdig","fryst lasagne","findus lasagne","toro lasagne"] },
  { navn: "Pasta ferdig", ikon: "🍝", kat: "frysevarer", alias: ["pasta ferdig","ferdigpasta","express pasta"] },
  { navn: "Suppe ferdig", ikon: "🍲", kat: "frysevarer", alias: ["ferdigsuppe","frossen suppe","toro ferdig"] },
  { navn: "Tacos kit", ikon: "🌮", kat: "tørrvarer", alias: ["tacos kit","old el paso","santa maria taco","taco mix"] },
  { navn: "Tacosaus", ikon: "🌮", kat: "tørrvarer", alias: ["tacosaus","salsa","santa maria salsa","old el paso salsa"] },
  { navn: "Tacoskjell", ikon: "🌮", kat: "tørrvarer", alias: ["tacoskjell","taco shells","hard taco","doritos taco"] },
  { navn: "Burrito", ikon: "🌯", kat: "tørrvarer", alias: ["burritos","burrito kit","santa maria burrito"] },
  { navn: "Tikka masala saus", ikon: "🍛", kat: "tørrvarer", alias: ["tikka masala","butter chicken saus","korma saus","rogan josh"] },
  { navn: "Wok saus", ikon: "🥢", kat: "tørrvarer", alias: ["wok saus","pad thai saus","teriyaki","sweet and sour"] },
  { navn: "Pizzasaus", ikon: "🍕", kat: "tørrvarer", alias: ["pizzasaus","pizza tomatsaus","cirio pizzasaus"] },
  { navn: "Pizza ferdig", ikon: "🍕", kat: "frysevarer", alias: ["pizza ferdig","grandiosa pizza","big one pizza"] },
  { navn: "Wok grønnsaker frossen", ikon: "🥢", kat: "frysevarer", alias: ["wokgrønnsaker","frossen wok","wok mix"] },
  { navn: "Dim sum", ikon: "🥟", kat: "frysevarer", alias: ["dumplings","gyoza","dim sum","potstickers"] },
  { navn: "Frossen edamame", ikon: "🫘", kat: "frysevarer", alias: ["edamame","frossen edamame","soyabønner"] },
  { navn: "Frossen mais", ikon: "🌽", kat: "frysevarer", alias: ["frossen mais","fryste maiskolber","baby corn frossen"] },
  { navn: "Frossen grønnsakssuppeblanding", ikon: "🥕", kat: "frysevarer", alias: ["suppegrønnsaker","frossen suppe grønnsaker","lapskaus grønnsaker"] },
  { navn: "Frossen vaffelrøre", ikon: "🧇", kat: "frysevarer", alias: ["vaffelrøre ferdig","frossen vaffelrøre","pinnekjøtt ferdig"] },
  { navn: "Pinnekjøtt", ikon: "🍖", kat: "kjott-fisk", alias: ["pinnekjøtt","salt pinnekjøtt","røkt pinnekjøtt"] },
  { navn: "Lutefisk", ikon: "🐟", kat: "kjott-fisk", alias: ["lutefisk","tørt lutefisk"] },
  { navn: "Raspeballer", ikon: "🥔", kat: "tørrvarer", alias: ["raspeballer","klubb","komle","raspepølse","raspeball mix"] },
  { navn: "Fårikål", ikon: "🐑", kat: "kjott-fisk", alias: ["fårikålkjøtt","lam til fårikål","fårikål"] },

  // ─── BABY & BARN ──────────────────────────────────────────────────────────
  { navn: "Morsmelkerstatning", ikon: "🍼", kat: "annet", alias: ["morsmelkerstatning","babymelk","novalac","aptamil","nan"] },
  { navn: "Barnemat", ikon: "🍼", kat: "annet", alias: ["barnemat","grøt baby","hipp organic","nestlé baby","fruktpuré baby"] },
  { navn: "Barnemat pose", ikon: "🍼", kat: "annet", alias: ["happyfood","little spoon","ella's kitchen","plum organics"] },
  { navn: "Risengrøt", ikon: "🍚", kat: "tørrvarer", alias: ["risengrøt","risen grøt","toro risengrøt","ris grøt"] },
  { navn: "Havrenøt", ikon: "🌾", kat: "tørrvarer", alias: ["havremos","havregrøt ferdig","toro havregrøt"] },
  { navn: "Barnepudding", ikon: "🍮", kat: "meieri", alias: ["egg pudding","sjokoladepudding","kremost pudding","melk pudding"] },
  { navn: "Juice box barn", ikon: "🧃", kat: "drikke", alias: ["juice boks","capri-sun","meny juice barn","fruktsaft boks"] },

  // ─── BAKEVARER ────────────────────────────────────────────────────────────
  { navn: "Sjokoladestykker", ikon: "🍫", kat: "tørrvarer", alias: ["sjokoladebiter","sjokoladedråper","chocolate chips","freia baker"] },
  { navn: "Sitronsyre", ikon: "🍋", kat: "tørrvarer", alias: ["sitronsyre","citric acid","askorbinsyre"] },
  { navn: "Gelatin", ikon: "🫙", kat: "tørrvarer", alias: ["gelatin","gelatinplater","agar agar"] },
  { navn: "Vaniljesaus", ikon: "🫙", kat: "tørrvarer", alias: ["vaniljesaus","engelsk saus","custard","freia vaniljesaus"] },
  { navn: "Vokse papir", ikon: "📦", kat: "hygiene", alias: ["bakepapir","vokset papir","non-stick baking"] },
  { navn: "Deig ferdig", ikon: "🥐", kat: "brod-bakeri", alias: ["croissant deig","smørdeig","butterdeig","puff pastry","phyllo"] },
  { navn: "Kakebunn", ikon: "🎂", kat: "brod-bakeri", alias: ["kakebunn","sukkerbrød","biskuitbunn","digestive bunn"] },
  { navn: "Glasur", ikon: "🎂", kat: "tørrvarer", alias: ["glasur","fondant","sukkerglasur","royal icing"] },
  { navn: "Maissirup", ikon: "🫙", kat: "tørrvarer", alias: ["gylden sirup","corn syrup","lyle's golden syrup"] },

  // ─── DIVERSE ANNET ────────────────────────────────────────────────────────
  { navn: "Fyrstikker", ikon: "🔥", kat: "annet", alias: ["fyrstikker","lighter","zippo"] },
  { navn: "Tannpirkere", ikon: "🪥", kat: "hygiene", alias: ["tannpirkere","tannstikker","toothpick"] },
  { navn: "Grilltennvæske", ikon: "🔥", kat: "annet", alias: ["grillkull","grilltenner","tennvæske","briketter"] },
  { navn: "Matvoks", ikon: "🕯️", kat: "annet", alias: ["bivoks","bienenwachs"] },
  { navn: "Partyservise", ikon: "🎉", kat: "annet", alias: ["papptallerkener","plastbestikk","engangsservise"] },
  { navn: "Husholdningsfilm", ikon: "📦", kat: "hygiene", alias: ["klintfilm","cling wrap","husholdningsfolie"] },
  { navn: "Isposer", ikon: "🧊", kat: "hygiene", alias: ["isposer","isbiter pose","ice bag"] },
  { navn: "Gummihansker", ikon: "🧤", kat: "hygiene", alias: ["gummihansker","latekshansker","vaskehansker"] },
  { navn: "Svamp", ikon: "🫧", kat: "hygiene", alias: ["oppvasksvamp","skurefille","scotch brite","vileda svamp"] },
  { navn: "WC rens", ikon: "🫧", kat: "hygiene", alias: ["toalettrens","wc rengjøring","duck toalett","bref"] },
  { navn: "Avløpsrens", ikon: "🫧", kat: "hygiene", alias: ["avløpsrens","drain cleaner","plumber","mr. muskel avløp"] },
  { navn: "Luftfriskner", ikon: "🌸", kat: "hygiene", alias: ["luftfriskner","febreze","airwick","ambi pur"] },
  { navn: "Muggsoppfjerner", ikon: "🫧", kat: "hygiene", alias: ["mugg spray","muggfjerning","domestos mold"] },
  { navn: "Glassvask", ikon: "🫧", kat: "hygiene", alias: ["glassvask","windex","window cleaner","pril glass"] },
  { navn: "Gulvvask", ikon: "🫧", kat: "hygiene", alias: ["gulvvask","gulvrengjøring","kärcher","floor cleaner"] },
  { navn: "Kalkfjerner", ikon: "🫧", kat: "hygiene", alias: ["kalkfjerner","kalkrens","viakal","cillit bang kalk"] },
  { navn: "Møbelpolish", ikon: "🫧", kat: "hygiene", alias: ["møbelpolish","pledge","furniture polish"] },
  { navn: "Klutepapir", ikon: "🧹", kat: "hygiene", alias: ["mikrofiberklut","rengjøringsklut","e-klut"] },
  { navn: "Vaskebøtte", ikon: "🧹", kat: "annet", alias: [] },
  { navn: "Mopp", ikon: "🧹", kat: "annet", alias: ["mopphodet","swiffer","gulvmopp"] },

  // ─── PÅLEGG ───────────────────────────────────────────────────────────────
  { navn: "Makrell i tomat", ikon: "🐟", kat: "kjott-fisk", alias: ["makrell i tomat","king oscar makrell","stabburet makrell"] },
  { navn: "Tunfisksalat", ikon: "🐟", kat: "kjott-fisk", alias: ["tunfisksalat","tuna salat","thai tuna"] },
  { navn: "Rekecocktail", ikon: "🦐", kat: "kjott-fisk", alias: ["rekecocktail","rekesalat","reke salat"] },
  { navn: "Kaviar", ikon: "🐟", kat: "kjott-fisk", alias: ["kaviar","kavli kaviar","rogn","lumpfish caviar"] },
  { navn: "Leverpostei fin", ikon: "🫙", kat: "kjott-fisk", alias: ["fin leverpostei","gilde leverpostei fin","stabbur lever"] },
  { navn: "Eggesalat", ikon: "🥚", kat: "kjott-fisk", alias: ["eggesalat","egg salat"] },
  { navn: "Rekesaus", ikon: "🦐", kat: "kjott-fisk", alias: ["rekesaus","prawn cocktail sauce"] },
  { navn: "Rakfisk", ikon: "🐟", kat: "kjott-fisk", alias: ["rakfisk","rakørret"] },
  { navn: "Skagen", ikon: "🦐", kat: "kjott-fisk", alias: ["skagenrøre","skagen pålegg"] },

  // ─── FERDIGMAT & HERMETIKK ────────────────────────────────────────────────
  { navn: "Soppsaus", ikon: "🍄", kat: "tørrvarer", alias: ["soppsaus","toro soppsaus","sjampinjongsaus"] },
  { navn: "Bernaisesaus", ikon: "🫙", kat: "tørrvarer", alias: ["bernaisesaus","béarnaise","toro bearnaise"] },
  { navn: "Hvit saus", ikon: "🫙", kat: "tørrvarer", alias: ["hvit saus","bechamelsaus","béchamel","ostesaus","toro hvit saus"] },
  { navn: "Grillsaus", ikon: "🫙", kat: "tørrvarer", alias: ["grillsaus","bbq sauce","hickory saus","smoky bbq"] },
  { navn: "Currysaus", ikon: "🍛", kat: "tørrvarer", alias: ["currysaus","toro curry","gul curry","rød curry"] },
  { navn: "Linsegryte", ikon: "🍲", kat: "tørrvarer", alias: ["linsegryte","dahl","dal","linsesuppe boks"] },
  { navn: "Grønnsakssup boks", ikon: "🍲", kat: "tørrvarer", alias: ["campbell's","heinz suppe","grønnsaksuppe boks","tomatsuppe boks"] },
  { navn: "Bønnesalsa", ikon: "🫘", kat: "tørrvarer", alias: ["bønnesalsa","svarte bønner boks","refried beans","bønner salsa"] },
  { navn: "Grønnsaker hermetikk", ikon: "🥫", kat: "tørrvarer", alias: ["hermetisk mais","hermetiske erter","hermetisk asparges"] },
  { navn: "Hermetisk laks", ikon: "🐟", kat: "kjott-fisk", alias: ["hermetisk laks","laks boks","john west laks"] },
  { navn: "Hermetisk makrell", ikon: "🐟", kat: "kjott-fisk", alias: ["makrell boks","hermetisk makrell","brisling boks"] },
  { navn: "Chili con carne", ikon: "🌶️", kat: "tørrvarer", alias: ["chili con carne","toro chili","santa maria chili"] },

  // ─── BAKST OG DESSERTER ───────────────────────────────────────────────────
  { navn: "Iskrem kulefryser", ikon: "🍦", kat: "frysevarer", alias: ["magnumkule","twister is","is kule","cornetto"] },
  { navn: "Iskaffe flaske", ikon: "☕", kat: "drikke", alias: ["nescafé iskaffe","starbucks frappuccino","gevalia iskaffe"] },
  { navn: "Sjokoladeis", ikon: "🍫", kat: "frysevarer", alias: ["sjokoladeis","brownie is","triple chocolate ice"] },
  { navn: "Sorbet", ikon: "🍧", kat: "frysevarer", alias: ["fruktsorbet","mango sorbet","sitronsorbet"] },
  { navn: "Panna cotta", ikon: "🍮", kat: "meieri", alias: ["panna cotta","pudding ferdig","creme brulee ferdig"] },
  { navn: "Krem dessert", ikon: "🍮", kat: "meieri", alias: ["rød grøt","sjokoladepudding ferdig","molten chocolate"] },
  { navn: "Klappekake mix", ikon: "🎂", kat: "tørrvarer", alias: ["kakemix","muffins mix","brownies mix","toro kake"] },
  { navn: "Pannekake mix", ikon: "🥞", kat: "tørrvarer", alias: ["pannekakemix","pancake mix","vaffelmix","toro pannekake"] },
  { navn: "Sjokoladesaus", ikon: "🍫", kat: "tørrvarer", alias: ["sjokoladesaus","sjokolade topping","hot fudge","hershey's"] },
  { navn: "Karamellsaus", ikon: "🍯", kat: "tørrvarer", alias: ["karamellsaus","dulce de leche","toffee sauce"] },
  { navn: "Vispekrem spray", ikon: "🍦", kat: "meieri", alias: ["sprøytefløte","whipped cream spray","redi whip"] },
  { navn: "Smørkrem", ikon: "🧈", kat: "tørrvarer", alias: ["smørkrem mix","buttercream","frosting"] },

  // ─── HELSE & VELVÆRE ──────────────────────────────────────────────────────
  { navn: "Proteinpulver", ikon: "💪", kat: "annet", alias: ["whey protein","proteinpulver","gainomax","bodylab protein"] },
  { navn: "Kreatin", ikon: "💪", kat: "annet", alias: ["kreatin","creatine","bodylab kreatin"] },
  { navn: "Omega 3", ikon: "🐟", kat: "hygiene", alias: ["omega-3","fish oil","tran","møllers tran","vitaepas"] },
  { navn: "Vitamin D", ikon: "☀️", kat: "hygiene", alias: ["vitamin d","d-vitamin","d3","vitamin d3"] },
  { navn: "Magnesium", ikon: "💊", kat: "hygiene", alias: ["magnesium tabletter","magnesium pulver"] },
  { navn: "Probiotika", ikon: "🦠", kat: "hygiene", alias: ["probiotika","lacteol","biola probiotika","culturelle"] },
  { navn: "Melatonin", ikon: "💊", kat: "hygiene", alias: ["melatonin","søvntabletter","circadin"] },
  { navn: "C-vitamin", ikon: "🍊", kat: "hygiene", alias: ["c-vitamin","vitamin c","ascorbinsyre","cebion"] },
  { navn: "Hårolje", ikon: "🧴", kat: "hygiene", alias: ["hårolje","argan olje","morocanoil","coconut hair oil"] },
  { navn: "Ansiktsmaske", ikon: "🧖", kat: "hygiene", alias: ["ansiktsmaske","face mask","sheet mask","clay mask"] },
  { navn: "Eksfoliant", ikon: "🧴", kat: "hygiene", alias: ["skrubb","eksfoliant","face scrub","body scrub"] },
  { navn: "Øyekrem", ikon: "🧴", kat: "hygiene", alias: ["øyekrem","eye cream","anti-age øye"] },
  { navn: "Serumm", ikon: "🧴", kat: "hygiene", alias: ["serum","hyaluronsyre serum","vitamin c serum","niacinamide"] },
  { navn: "Bronsepulver", ikon: "💄", kat: "hygiene", alias: ["selvbruner","tan lotion","st tropez","cocoa brown"] },

  // ─── SISTE ────────────────────────────────────────────────────────────────
  { navn: "Smørsauser", ikon: "🧈", kat: "tørrvarer", alias: ["smørsaus","hollandaise","toro hollandaise"] },
  { navn: "Grønnsaksbuljong", ikon: "🫙", kat: "tørrvarer", alias: ["grønnsaksbuljong","vegansk buljong","knorr grønnsak"] },
  { navn: "Soppbuljong", ikon: "🍄", kat: "tørrvarer", alias: ["soppbuljong","mushroom stock","fungi buljong"] },
  { navn: "Kjøttbuljong", ikon: "🫙", kat: "tørrvarer", alias: ["kjøttbuljong","oksekraft","biff fond","brune fond"] },
  { navn: "Fiskebuljong", ikon: "🐟", kat: "tørrvarer", alias: ["fiskebuljong","fiskefond","fish stock"] },
  { navn: "Sitrongress", ikon: "🌿", kat: "frukt-gront", alias: ["sitrongress","lemongrass","citrongress"] },
  { navn: "Kaffir lime blad", ikon: "🌿", kat: "frukt-gront", alias: ["kaffir lime","lime blad","combava"] },
  { navn: "Wasabi", ikon: "🌿", kat: "tørrvarer", alias: ["wasabi","wasabipasta","japansk pepperrot"] },
  { navn: "Pickles", ikon: "🫙", kat: "tørrvarer", alias: ["pickles","sylteagurk","cornichons","kimchi"] },
  { navn: "Kimchi", ikon: "🥬", kat: "tørrvarer", alias: ["kimchi","koreansk kimchi"] },
  { navn: "Mirin", ikon: "🫙", kat: "tørrvarer", alias: ["mirin","sake","risvin"] },

];

// Lager et oppslagsverk for rask matching
export const PRODUCT_ALIAS_MAP = {};
for (const p of PRODUCTS) {
  for (const alias of p.alias) {
    PRODUCT_ALIAS_MAP[alias.toLowerCase()] = p;
  }
  PRODUCT_ALIAS_MAP[p.navn.toLowerCase()] = p;
}

/**
 * Matcher en kvitteringslinje mot produktdatabasen.
 * Returnerer produktet hvis funnet, ellers null.
 */
export function matchProduct(line) {
  if (!line) return null;
  const normalized = line.toLowerCase()
    .replace(/[0-9]+[,.]?[0-9]*\s*(kg|g|l|dl|ml|stk|pk|x)\b/gi, "")
    .replace(/[^a-zæøå\s]/gi, " ")
    .replace(/\s+/g, " ")
    .trim();

  // 1. Eksakt match på alias
  if (PRODUCT_ALIAS_MAP[normalized]) return PRODUCT_ALIAS_MAP[normalized];

  // 2. Sjekk om noen alias er inneholdt i linjen
  let best = null;
  let bestLen = 0;
  for (const [alias, product] of Object.entries(PRODUCT_ALIAS_MAP)) {
    if (normalized.includes(alias) && alias.length > bestLen) {
      best = product;
      bestLen = alias.length;
    }
  }
  return best;
}

/**
 * Gjetter kategori fra produktnavn ved hjelp av databasen.
 * Fallback til "annet".
 */
export function guessCategoryFromDB(name) {
  const match = matchProduct(name);
  return match ? match.kat : null;
}

// Append more products (replace the closing bracket before this)
